### PR TITLE
Request115

### PR DESCRIPTION
**Pull request by JackGruber**
Update Code from "[WIP] Refactor php code #115"

### CODE REVIEW

**Comment by dgiese** [comment]
Is this still WIP or working?

**Comment by JackGruber** [comment]
i think we are waiting with the PULL, at the moment it doesn't offer any additional value and maybe we should work on it first?

what do you think @tetreum ?

**Comment by tetreum** [comment]
@dgiese If im not wrong, @JackGruber finished the missing parts, so it should be fully working :)
@JackGruber code refactors are made to improve the code rather than add new features so it's normal that it doesn't have any additional value no?

**Comment by JackGruber** [comment]
I create a new pull request with no conflicts.

**Pull request closed without merging**
