### PR TITLE
[WIP] Refactor php code

### PR DESCRIPTION
**Pull request by tetreum**
**WORK IN PROGRESS**

Refactor php code to make it more easier to maintain:
- Moved to PSR-4 specification so we can avoid manually making multiple requires on each file.
- Config constants have been replaced for `App::config("CONFIG_VAR_NAME")`.
- Random functions have been moved to static Utils class.
- MySQL connection is now instanced (not useful right now as current content is quite simple).

**ToDo**
- Add a templating system to separate html from php
- Replace pretty print function with `p`
- Edit readme.md to tell that `composer` (getcomposer.org) is now required
- Replace remaining constants to `App::config("CONFIG_VAR_NAME")`
- UI Installer script to do all setup steps from https://github.com/dgiese/dustcloud/wiki/Dustcloud-Installation#installation-server

I do really want this project to succeed as i don't like to being tied to an external service to manage my devices!

### CODE REVIEW

**Comment by dgiese** [comment]
Lots of changes. Do they break anything?

**Comment by JackGruber** [comment]
after a quick check:

autoload.php is missing
conf.sample.php syntax error on line 15/16, missing comma
no PHP ending Tags

**Comment by tetreum** [comment]
Hey, its a work in progress, its not finished/not meant to be merged.
About the no ending tags, it's part of the PSR spec :S Pretty common:
https://www.php-fig.org/psr/psr-2/ => `The closing ?> tag MUST be omitted from files containing only PHP.`

**Comment by JackGruber** [comment]
I made some changes to your Pull request. Now everything works as before. 
But how can I contribute my changes to your Pull request?

**Comment by tetreum** [comment]
@JackGruber I think you have to send the PR to https://github.com/tetreum/dustcloud so i can merge it in this PR

**Comment by JackGruber** [comment]
@tetreum I have create a new Pull request (#120)
This contains the code from you and the changes.

**Comment by tetreum** [comment]
Ok! closing this PR

**Pull request closed without merging**
