### PR TITLE
Some fixes for imagebuilder

### PR DESCRIPTION
**Pull request by cryptomilk**
* Fix help messages
* Fix permissons
* Make soundfile optional

### CODE REVIEW

**Comment by cryptomilk** [comment]
The failure is not related to my changes. They don't modify flasher.py. flake8 complains about a code comment ...

**Comment by cryptomilk** [comment]
Ping :-)

**Comment by dgiese** [comment]
Interesting pull request. But if the Soundlang stuff is used, how the sound is actually enabled afterwards?

**Comment by cryptomilk** [comment]
I haven't figured out the soundlang part yet. If you don't set it, it will overwrite the english sound files.

**Comment by cryptomilk** [comment]
I've updated it an removed the soundlang option. With this specifying a soundfile isn't required anymore but you can replace the english lang with it.

**Pull request merged**
