### PR TITLE
Remove root from build process

### PR DESCRIPTION
**Pull request by deisi**
With fuse-ext2 it is possible to mount and manipulate the firmware image as
user. I further added a sync call before unmounting as this flushes the cache of
the firmware image.

For me this change was necessary as I use Arch Linux with btrfs filesystem and I couldn't mount the ext4 filesystem otherwise.  

***Disclaimer***
I have not tested the firmware that resulted from this, as I don't want to brick my vacuum and my knowledge of recovering is limited. If somebody with more knowledge about this gives me a go and possibly some help in case of failure, I would of course test this.
Further I don't know what consequences these changes have on Mac OSX.

### CODE REVIEW

**Comment by deisi** [comment]
Okay, I was brave and just flashed it. As far as I can see everything works fine.

**Comment by fvollmer** [comment]
Great!
I think this is a good idea. The files created by the old files were always owned by root, which sometimes caused issues (e.g. you had to do

**Comment by deisi** [comment]
yes that is true, I also discovered a strange thing. Valetudo is working, but I cant ssh on the machine as of right now. I'm not sure what is causing it tough, as the public ssh key is part if the image.

**Comment by deisi** [comment]
Okay, now I'm sure this definitely adds a bug where one cant ssh on the machine any more. Now lets find out why the ssh key is not accepted when the firmware is build as user.

**Comment by slaecker** [comment]
Maybe wrong ownership of.ssh folder or authorized_keys file?
- ~/.ssh must be 700
    - authorized_keys must be 600

Just a blind guess.

**Comment by dgiese** [comment]
Yeah, the authorized_keys file must be owned by root...which can be an issue if you are not root while you create the image...

**Comment by deisi** [comment]
how about I add a script that changes owner ship of authorized_keys upon booting of the vacuum. This way the amount of root executed code would at least shrink down to a bare minimum. Or is the filesystem read only?

**Comment by fvollmer** [comment]
I have no experience with ext2-fuse, but what happens if you just add `chown root:root $IMG_DIR/root/.ssh` and `chown root:root $IMG_DIR/root/.ssh/authorized_keys` to the build script?

**Comment by deisi** [comment]
doesn't work. you need root to do so.

**Comment by fvollmer** [comment]
Are you sure? I just tried it my self and it appears to work.

grafik

**Comment by deisi** [comment]
Screenshot from 2019-05-07 20-31-37

where is the difference?

**Comment by fvollmer** [comment]
This is surprising to me. The only difference I can spot is the slightly different mount command, but this doesn't explain the `Operation not permitted` error. Does `dmesg` show any error? What OS are you using?

**Comment by deisi** [comment]
`dmesg` looks fine. I'm on Arch Linux. Maybe something about the user groups:

```
[malte@mtop image]$ groups 
sys lock bumblebee network power gdm wireshark users video uucp storage lp input audio wheel malte snapper
```

**Comment by fvollmer** [comment]
```
fvollmer@debian-fvollmer:~$ groups
fvollmer cdrom floppy sudo audio dip video plugdev netdev lpadmin scanner vboxsf
```

**Comment by deisi** [comment]
I have no clue what so ever o.O

**Comment by fvollmer** [comment]
Check if the mount option `default_permissions` is active. (type `mount`)

**Comment by deisi** [comment]
I think you found the reason:
/home/malte/Projects/rockrobo/image/fw.pTK2yP/fw/disk.img on /home/malte/Projects/rockrobo/image/fw.pTK2yP/image type fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000,default_permissions,allow_other)

So if there is no way to turn off default_permission this won't work.

**Comment by fvollmer** [comment]
I used Arch Linux in a VM and patched `fuse-ext2` to disable `default_permissions`. It now works:
grafik
I guess the best way would be to fix `fuse-ext2` upstream. I won't have the time to do this.

**Comment by fvollmer** [comment]
I'm not sure if we should worry, but there is this big warning in the `README.md`
> Even though write support is available, please do not mount your filesystems with write support unless you have nothing to lose.

**Comment by dgiese** [comment]
After reading the comments, I do not really feel comfortable to change the building system. While it is not nice to do it with root permissions, we at least know that it somehow works reliable. Not having ext4/ext3/ext2 support compiled in the kernel seems for me to be an edge case (correct me if I am wrong)...

**Comment by cryptomilk** [comment]
I agree with @dgiese :-)

**Comment by deisi** [comment]
Okay, Then I close this. Maybe at some point we have a better way.

**Pull request closed without merging**
