### PR TITLE
Fix troubles with readlink on macOS.

### PR DESCRIPTION
**Pull request by int-0x03**
All tested on macOS Mojave 10.14.3. All working.
image

### CODE REVIEW

**Comment by cryptomilk** [comment]
I'm sorry but this makes the code much more complex and there is a simpler solution to that. Just add a readlink function to the script for operating system which aren't really operating systems:

```
readlink() {
    path=$1

    if [ -L "$path" ]
    then
        ls -l "$path" | sed 's/^.*-> //'
    else
        return 1
    fi
}
```

**Comment by int-0x03** [comment]
If place all chekings in common block for darwin-systems, all will be nice. but whatever.

**Comment by cryptomilk** [comment]
What about https://github.com/cryptomilk/dustcloud/commits/master-readlink

**Comment by GH0st3rs** [comment]
Don't panic, be happy
```bash
alias readlink=greadlink
```

**Comment by dgiese** [comment]
Cant afford a Mac. Can someone who uses a mac confirm, that it works? ;)

**Comment by cryptomilk** [comment]
That's why I suggested to just implement the readlink_f() in bash. Then it will work on all platforms ...

See https://github.com/cryptomilk/dustcloud/commits/master-readlink

**Comment by dgiese** [comment]
So is this pull working for all MacOS without breaking somthing?

**Comment by int-0x03** [comment]
I will test later, wait pls

**Comment by cryptomilk** [comment]
https://github.com/cryptomilk/dustcloud/commits/master-readlink has been already pushed upstream.

**Comment by int-0x03** [comment]
Ok, just remove this pull.

**Pull request closed without merging**
